_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
Augmentation:
    value: "Yes"
Standardization:
    value: "Yes"
architecture:
    value: DenseNet121
data samples:
    value: 10000
dataset:
    value: CheXpert
epochs:
    value: 20
learning_rate:
    value: 0.001
